real
spring:
  profiles: real
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spg?serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 80