spring:
  profiles:
    active: local

# local 환경
---
spring:
  profiles: local
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format: true

server:
  port: 8000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# 운영 환경
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8021

# real
---
spring:
  profiles: real
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8022